Remove cxl.h formerly used for systems not having uptodate kernel headers or using simulation on non powerpc systems
cxl.h is not licences under the Apache 2.0 license. Therefore having a
copy in this repository is not desired. Furthermore, it could even be
that there is a newer copy of the file already existing on kernel.org.
The problem with this file is that e.g. libcxl tried to do a wget to
download the file before building the code automatically. That is not
working in setups without internet access. Also it might just use whatever
version of this file. Removing it here, is the first step to get this right.

diff --git a/lib/Makefile b/lib/Makefile
--- a/lib/Makefile
+++ b/lib/Makefile
@@ -77,10 +77,16 @@ $(libcxl_a): ..check_libcxl
 		echo;							\
 		exit 1;							\
 	fi
-	@if [ ! -f $(CONFIG_LIBCXL_PATH)/include/misc/cxl.h ]; then	\
-		mkdir -p $(CONFIG_LIBCXL_PATH)/include/misc/;		\
-		cp ../ext/include/misc/cxl.h 				\
-			$(CONFIG_LIBCXL_PATH)/include/misc/cxl.h;	\
+	@if [ ! -f /usr/include/misc/cxl.h ]; then			\
+		printf  "\t[ERROR]\t/usr/include/misc/cxl.h not found!\n";\
+		echo;							\
+		echo "  Please ensure you are having up-todate";	\
+		echo "  kernel-headers when building the code.";        \
+		echo "  When using pslse, get a recent copy of the file";\
+		echo "  from kernel.org and copy the file manually to";	\
+		echo "  $(CONFIG_LIBCXL_PATH)/include/misc/cxl.h.";	\
+		echo;							\
+		exit 1;							\
 	fi
 
 endif	# WITH_LIBCXL
