Add best and fast options and fixup whitespace

diff --git a/tools/genwqe_file_perf b/tools/genwqe_file_perf
--- a/tools/genwqe_file_perf
+++ b/tools/genwqe_file_perf
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# Copyright 2015, 2016, International Business Machines
+# Copyright 2016, International Business Machines
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -16,18 +16,8 @@
 # limitations under the License.
 #
 
-#
-# This testcase proceses significant interrupt stress. Run that for a day
-# and you will know if your device driver and software can surive sudden
-# abborts while running a lot of interrrupt stress.
-#
-# Start N echos and kill them after a couple of seconds.
-#
-
 card=0
 verbose=0
-iterations=1
-count=1
 PLATFORM=`uname -p`
 start_time=`date`
 options=""
@@ -47,17 +37,17 @@ fi
 
 function usage() {
     echo "Usage:"
-    echo "  genwqe_parallel_echo"
+    echo "  genwqe_file_perf"
     echo "    [-A] <accelerator> GENWQE|CAPI"
-    echo "    [-C] <card>        card to be used for the test"
-    echo "    [-c] <count>       send <count> echos and than stop"
-    echo "    [-i] <iterations>  repeat  multiple times for more testing"
-    echo "    [-t] <test_data>   file to use for performance measurement"
-    echo "    [-k]               keep output data and write to filesystem"
+    echo "    [-C] <card>	 card to be used for the test"
+    echo "    [-t] <test_data>	 file to use for performance measurement"
+    echo "    [-1] --fast mode for compression"
+    echo "    [-9] --best mode for compression"
+    echo "    [-k]		 keep output data and write to filesystem"
     echo "    [-l] Enable system load logging"
-    echo "         sadc - System activity data collector and gnuplot"
-    echo "         must be installed"
-    echo "    [-v]               verbose"
+    echo "	   sadc - System activity data collector and gnuplot"
+    echo "	   must be installed"
+    echo "    [-v]		 verbose"
     echo
     echo "To exclude influences from reading and writing to disk,"
     echo "it is recommended to create a ramdisk e.g. by using tmpfs"
@@ -69,18 +59,18 @@ function usage() {
 
 function erase_files() {
     for s in ${sizes} ; do
-        rm -f ${s}KiB.bin ${s}KiB.orig ${s}KiB.gz out.stderr
+	rm -f ${s}KiB.bin ${s}KiB.orig ${s}KiB.gz out.stderr
     done
     rm -f system_load.sar system_load.csv system_load.txt system_load.gnuplot
 }
 
 function cleanup() {
     if [ $logging -eq 1 ]; then
-        system_load_logging_stop
+	system_load_logging_stop
     fi
     echo "EXIT ..."
 }
-  
+
 trap cleanup SIGINT
 trap cleanup SIGKILL
 trap cleanup SIGTERM
@@ -133,7 +123,7 @@ EOF
     mv system_load.pdf system_load.${ZLIB_ACCELERATOR}.pdf
 }
 
-while getopts "A:C:c:t:kli:vh" opt; do
+while getopts "19A:C:t:klvh" opt; do
     case $opt in
 	A)
 	accelerator=$OPTARG;
@@ -141,11 +131,14 @@ while getopts "A:C:c:t:kli:vh" opt; do
 	C)
 	card=$OPTARG;
 	;;
-	c)
-	count="-c $OPTARG";
-	;;
 	t)
 	test_data=${OPTARG};
+	;;
+	1)
+	options+=" -1"
+	;;
+	9)
+	options+=" -9"
 	;;
 	l)
 	logging=1;
@@ -153,27 +146,24 @@ while getopts "A:C:c:t:kli:vh" opt; do
 	k)
 	keep=1;
 	;;
-        i)
-        iterations=$OPTARG;
-        ;;
 	b)
 	verbose=1;
 	;;
-        h)
-        usage;
-        exit 0;
-        ;;
+	h)
+	usage;
+	exit 0;
+	;;
 	t)
 	tools_dir=$OPTARG;
 	;;
-        \?)
-        echo "Invalid option: -$OPTARG" >&2
-        ;;
+	\?)
+	echo "Invalid option: -$OPTARG" >&2
+	;;
     esac
 done
 
 if [ ${accelerator} = SW ]; then
-    options="-s"
+    options+=" -s"
 fi
 
 ZLIB_ACCELERATOR=${accelerator}
@@ -199,42 +189,40 @@ fi
 
 echo "KiB ; sec ; sec"
 for s in ${sizes} ; do
-    for i in `seq 1 ${iterations}` ; do
-	if [ ${keep} -eq 1 ]; then
-            outfile=${s}KiB.orig
-        else
-            outfile=/dev/null
-        fi
+    if [ ${keep} -eq 1 ]; then
+	outfile=${s}KiB.orig
+    else
+	outfile=/dev/null
+    fi
 
-        sync
-        (time genwqe_gzip -A ${accelerator} ${options} -C ${card} -c \
-            ${s}KiB.bin > ${s}KiB.gz) 2> out.stderr 
-        if [ $? -ne 0 ]; then
-	    echo "Compression failed ..."
-	    exit 1
-        fi
+    sync
+    (time genwqe_gzip -A ${accelerator} ${options} -C ${card} -c \
+	${s}KiB.bin > ${s}KiB.gz) 2> out.stderr
+    if [ $? -ne 0 ]; then
+	echo "Compression failed ..."
+	exit 1
+    fi
 
-	c=`grep real out.stderr | cut -f2 -d'm' | cut -d's' -f1`;
-	if [ $verbose -eq 1 ]; then
-		cat out.stderr
-	fi
+    c=`grep real out.stderr | cut -f2 -d'm' | cut -d's' -f1`;
+    if [ $verbose -eq 1 ]; then
+	cat out.stderr
+    fi
 
-        sync
-        (time genwqe_gunzip -A ${accelerator} -o512KiB ${options} -C ${card} \
-            -c ${s}KiB.gz > ${outfile}) 2> out.stderr
-        if [ $? -ne 0 ]; then
-	    echo "Decompression failed ..."
-	    exit 1
-        fi
+    sync
+    (time genwqe_gunzip -A ${accelerator} -o512KiB ${options} -C ${card} \
+	-c ${s}KiB.gz > ${outfile}) 2> out.stderr
+    if [ $? -ne 0 ]; then
+	echo "Decompression failed ..."
+	exit 1
+    fi
 
-	d=`grep real out.stderr | cut -f2 -d'm' | cut -d's' -f1`;
-	if [ $verbose -eq 1 ]; then
-		cat out.stderr
-	fi
+    d=`grep real out.stderr | cut -f2 -d'm' | cut -d's' -f1`;
+    if [ $verbose -eq 1 ]; then
+	cat out.stderr
+    fi
 
-        echo "${s} ; ${c} ; ${d}"
-	rm -f ${s}KiB.orig ${s}KiB.gz out.stderr
-    done
+    echo "${s} ; ${c} ; ${d}"
+    rm -f ${s}KiB.orig ${s}KiB.gz out.stderr
 done
 
 if [ $logging -eq 1 ]; then
